version: 0.1.{build}
image: Visual Studio 2017

environment:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  matrix:
    - platform: x86
      configuration: Release
      cmake_generator: "Visual Studio 15 2017"
      msbuild_property: win32
    - platform: x64
      configuration: Release
      cmake_generator: "Visual Studio 15 2017 Win64"
      msbuild_property: x64
    - platform: x86
      configuration: Debug
      cmake_generator: "Visual Studio 15 2017"
      msbuild_property: win32
    - platform: x64
      configuration: Debug
      cmake_generator: "Visual Studio 15 2017 Win64"
      msbuild_property: x64

build_script:
- cmd: >-
    set BOOST_ROOT=C:\Libraries\boost_1_66_0

    cmake -DCMAKE_BUILD_TYPE=%configuration% -G "%cmake_generator%" .

    cmake --build . --target src/test/Tests -- /property:Configuration=%configuration% /property:Platform=%msbuild_property%

    cmake --build . --target src/benchmark/Benchmark -- /property:Configuration=%configuration% /property:Platform=%msbuild_property%
test_script:
- cmd: >-
    ctest

    src\benchmark\%configuration%\Benchmark.exe
shallow_clone: true
